name: Swift Integration Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: "6.0"

    - name: Build server
      run: |
        cd Tests/testing-servers
        swift build -c release

    - name: Start server in background
      run: |
       cd Tests/testing-servers/.build/release/App &
        echo $! > server.pid

    - name: Wait for server to be ready
      run: |
        for i in {1..10}; do
          if lsof -i :6500 > /dev/null; then
            echo "✅ Server is ready"
            exit 0
          else
            echo "⏳ Waiting for server..."
            sleep 2
          fi
        done
        echo "❌ Server did not start in time"
        exit 1

    - name: Run tests
      run: |
        swift build
        swift test

    - name: Stop server
      run: |
        kill $(cat server.pid)
